### ISSUE TITLE
new order stop maket error

### ISSUE THREAD

**Issue by qiudaozhang** [binance/binance-futures-connector-python#41] opened 2022-07-18 09:56 UTC
here is my code

```python
params = {
                "positionSide": "LONG",
                "stop_price": stop_price 
            }
# s eq BTCUSDT
self.client.new_order(symbol=s, side="SELL", type="STOP_MARKET",
                      **params)
```

error is 

1102, 'A mandatory parameter was not sent, was empty/null, or malformed.'

According to the API description, are not all the necessary parameters passed?

**Comment by qiudaozhang** [comment] 2022-07-18 10:44
My mistake stop_price=> stopPrice

**Comment by Augustine-Charly** [comment] 2022-07-20 14:40
Looks like the issue is self resolved, good job. Kindly close the issue.

**Closed** 2022-07-22 11:06 UTC
